machine:
  python:
    version: 2.7.10
dependencies:
  pre:
    pip install -r requirements.txt
branches:
  only:
  - chore-coderefactor
  - develop
  - master
# Add some environment variables
environment:
  CIRCLE_ENV: test
  DATABASE_URL:  sqlite:///test/test.db
  SECRET_KEY: secrets