language: python
python:
  - "2.7"
before_install:
  - "pip install -r requirements.txt"
  - cp .env.travis .env
install:
  - "pip install coveralls"
script:
  - nosetests --with-coverage
after_success:
  - coveralls
branches:
  only:
  - chore-coderefactor
  - develop
  - master
services:
  - sqlite
